# Generated by Django 2.1.5 on 2019-02-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_remove_participant_team'),
        ('join_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_info',
            name='person_info',
        ),
        migrations.RemoveField(
            model_name='team_info',
            name='team_event',
        ),
        migrations.DeleteModel(
            name='team_info',
        ),
    ]
