# Generated by Django 2.1.5 on 2019-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_team', '0003_team_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='submission',
            field=models.IntegerField(default=0),
        ),
    ]
