# Generated by Django 2.1.5 on 2019-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_team', '0005_auto_20190521_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_info',
            old_name='submission',
            new_name='submission_A',
        ),
        migrations.AddField(
            model_name='team_info',
            name='submission_B',
            field=models.IntegerField(default='0'),
        ),
    ]
