# Generated by Django 2.1.5 on 2019-02-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competition_topic',
            fields=[
                ('com_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=20)),
                ('com_details', models.TextField()),
                ('com_end_time', models.DateField()),
            ],
        ),
    ]
