# Generated by Django 2.1.5 on 2019-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_team', '0001_initial'),
        ('sign_up', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ManyToManyField(to='join_team.team_info'),
        ),
    ]
