# Generated by Django 2.1.5 on 2019-02-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join_team', '0003_team_info'),
        ('sign_up', '0004_remove_participant_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='join_team.team_info'),
        ),
    ]
