# Generated by Django 2.1.5 on 2019-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_participant_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition_topic',
            name='data_set_file',
            field=models.CharField(default='', max_length=100),
        ),
    ]
