# Generated by Django 2.1.5 on 2019-04-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('sign_up', '0006_competition_topic_data_set_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_details',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.normal_user')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
