# Generated by Django 2.1.5 on 2019-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0007_address_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_details',
            old_name='id',
            new_name='user_id',
        ),
    ]
