# Generated by Django 2.1.5 on 2019-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0008_auto_20190408_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition_topic',
            old_name='data_set_file',
            new_name='data_set_file_A',
        ),
        migrations.AddField(
            model_name='competition_topic',
            name='data_set_file_B',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='competition_topic',
            name='data_set_file_trainnig',
            field=models.CharField(default='', max_length=100),
        ),
    ]
