# Generated by Django 2.1.5 on 2019-05-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0012_auto_20190523_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition_topic',
            name='TestA_open_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competition_topic',
            name='TestB_open_time',
            field=models.DateField(auto_now=True),
        ),
    ]
