# Generated by Django 2.1.5 on 2019-05-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0015_auto_20190523_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition_topic',
            name='money_to_pay',
            field=models.IntegerField(default='500'),
        ),
    ]
