# Generated by Django 2.1.5 on 2019-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_topic', models.CharField(max_length=50)),
                ('video_urls', models.CharField(max_length=100)),
            ],
        ),
    ]
