# Generated by Django 2.1.5 on 2019-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
