# Generated by Django 2.1.5 on 2019-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='', max_length=5),
        ),
    ]
