# Generated by Django 2.1.5 on 2019-05-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_news', '0002_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='study_resource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=4)),
            ],
        ),
    ]
