# Generated by Django 2.1.5 on 2019-05-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_news', '0003_study_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_resource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
