# Generated by Django 2.1.5 on 2019-05-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('Info_news', '0004_auto_20190502_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info_content', models.CharField(max_length=200)),
                ('now_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.normal_user')),
            ],
        ),
    ]
