# Generated by Django 2.1.5 on 2019-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_news', '0005_system_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='now_date',
            field=models.DateTimeField(),
        ),
    ]
