# Generated by Django 2.1.5 on 2019-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_news', '0006_auto_20190502_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='now_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
